### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by kampit** [codeboxrcodehub/coupondiscount#2]
```
Problem 1
    - Root composer.json requires codeboxr/coupondiscount * -> satisfiable by codeboxr/coupondiscount[v1.0.2, v1.0.3].
    - codeboxr/coupondiscount[v1.0.2, ..., v1.0.3] require illuminate/database ^8.83 -> found illuminate/database[v8.83.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
```

**Comment by dipudey** [comment]
@kampit 

Thanks, I'm able to reproduce this issue. We fixed this issue on the release of a new version v1.0.4. Now you can't install and check it.

**Comment by dipudey** [comment]
@kampit 

Thanks, I'm able to reproduce this issue. We fixed this issue on the release of a new version v1.0.4. Now you can install and check it.
