### ISSUE TITLE
Coupon::apply throw error

### ISSUE THREAD

**Issue by nayre1** [codeboxrcodehub/coupondiscount#4]
```
try {
      Coupon::apply([
               "code"        => $coupon, // coupon code. (required)`
                "amount"      => $amount, // total amount to apply coupon. must be a numberic number (required)
                "user_id"     =>$user_id, // user id (required)
                "order_id"    => $order_id, // order id (required)
      ]);
} catch (\Exception $e) {
}
```
This function throw error:
`Codeboxr\CouponDiscount\Services\CouponValidityService::validity(): Argument #6 ($vendorId) must be of type ?string, array given, called in \vendor\codeboxr\coupondiscount\src\Services\CouponService.php on line 192`

**Comment by nayre1** [comment]
Can bypass it using
```
                "device_name"    => 'spp',
                "ip_address"    => '127.0.0.1',
                "skip" => 'vendor_id'
```
But ...

**Comment by cyparthi** [comment]
public function apply(array $data)
    {
        $this->applyValidation($data);

        $code       = $data["code"];
        $amount     = $data["amount"];
        $userId     = $data["user_id"];
        $orderId    = $data["order_id"];
        $deviceName = isset($data['device_name']) ? $data['device_name'] : null;
        $ipaddress  = isset($data['ip_address']) ? $data['ip_address'] : null;
        $vendorId  = isset($data['vendor_id']) ? $data['vendor_id'] : null;  //  this value is missing
        $skipFields = isset($data['skip']) ? $data['skip'] : [];

        // check applied coupon code code validity
        $couponValidity = $this->validity($code, $amount, $userId, $deviceName, $ipaddress,$vendorId,$skipFields);
